title: Good 的博客
author:
  name: 刘曾好
  email: liuzengh@qq.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  本网站的文章如非注明转载均为原创。
  本网站所有原创文章使用 Creative Commons 署名-相同方式共享 4.0 国际协议许可证进行许可，如需其他使用请事先联系我。
  
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# minima:
#   social_links:
#     - { platform: github,         user_url: "https://github.com/liuzengh" }