title: "The Curious Explorer: A Personal Adventure"
author:
  name: goodliu
  email: liuzengh@qq.com

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme



minima:
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }