title: "The Curious Explorer: A Personal Adventure"
author:
  name: goodliu
  email: liuzengh@qq.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# github_username:  jekyll

minima:
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }